/**
 * ENGLISH QUEST - Word Repository
 * 1000 common English words organized in 10 categories with difficulty ratings.
 * SOLID: Single Responsibility — this module ONLY provides word data.
 * Each word includes a preloaded Spanish translation to minimize API calls.
 */

// Pre-translated Spanish equivalents for instant lookup (avoids API calls for game flow)
const PRELOADED_TRANSLATIONS = {
  "absolutely": "absolutamente",
  "afternoon": "tarde",
  "again": "otra vez",
  "airport": "aeropuerto",
  "all": "todo",
  "almost": "casi",
  "already": "ya",
  "alright": "bien",
  "also": "también",
  "always": "siempre",
  "another": "otro",
  "anyone": "cualquiera",
  "apple": "manzana",
  "ask": "preguntar",
  "baby": "bebé",
  "bad": "malo",
  "banana": "plátano",
  "be": "ser",
  "beach": "playa",
  "bear": "oso",
  "beautiful": "hermoso",
  "become": "convertirse",
  "begin": "comenzar",
  "big": "grande",
  "bird": "pájaro",
  "boss": "jefe",
  "boy": "niño",
  "bread": "pan",
  "breakfast": "desayuno",
  "bridge": "puente",
  "bright": "brillante",
  "brother": "hermano",
  "bus": "autobús",
  "call": "llamar",
  "cat": "gato",
  "change": "cambiar",
  "cheese": "queso",
  "chicken": "pollo",
  "child": "niño",
  "city": "ciudad",
  "clean": "limpio",
  "cloud": "nube",
  "code": "código",
  "coffee": "café",
  "come": "venir",
  "company": "empresa",
  "computer": "computadora",
  "contract": "contrato",
  "dark": "oscuro",
  "data": "datos",
  "database": "base de datos",
  "daughter": "hija",
  "dessert": "postre",
  "different": "diferente",
  "difficult": "difícil",
  "dinner": "cena",
  "dirty": "sucio",
  "do": "hacer",
  "doctor": "médico",
  "dog": "perro",
  "download": "descargar",
  "each": "cada",
  "ear": "oreja",
  "easy": "fácil",
  "egg": "huevo",
  "email": "correo electrónico",
  "enough": "suficiente",
  "evening": "noche",
  "every": "cada",
  "everything": "todo",
  "everywhere": "en todas partes",
  "exactly": "exactamente",
  "excuse me": "disculpe",
  "exercise": "ejercicio",
  "eye": "ojo",
  "face": "cara",
  "family": "familia",
  "far": "lejos",
  "fast": "rápido",
  "father": "padre",
  "feel": "sentir",
  "file": "archivo",
  "find": "encontrar",
  "fine": "bien",
  "first": "primero",
  "fish": "pez",
  "flight": "vuelo",
  "flower": "flor",
  "folder": "carpeta",
  "foot": "pie",
  "forest": "bosque",
  "fox": "zorro",
  "friend": "amigo",
  "fruit": "fruta",
  "get": "obtener",
  "girl": "niña",
  "give": "dar",
  "go": "ir",
  "good": "bueno",
  "good morning": "buenos días",
  "good night": "buenas noches",
  "goodbye": "adiós",
  "hand": "mano",
  "happy": "feliz",
  "hard": "duro",
  "have": "tener",
  "head": "cabeza",
  "healthy": "saludable",
  "hear": "oír",
  "heart": "corazón",
  "hello": "hola",
  "help": "ayudar",
  "here": "aquí",
  "high": "alto",
  "horse": "caballo",
  "hospital": "hospital",
  "hotel": "hotel",
  "how": "cómo",
  "how are you": "cómo estás",
  "husband": "esposo",
  "inside": "dentro",
  "internet": "internet",
  "job": "trabajo",
  "juice": "jugo",
  "just": "solo",
  "keyboard": "teclado",
  "know": "saber",
  "last": "último",
  "later": "después",
  "learn": "aprender",
  "lemon": "limón",
  "like": "gustar",
  "lion": "león",
  "live": "vivir",
  "long": "largo",
  "look": "mirar",
  "lose": "perder",
  "loud": "ruidoso",
  "low": "bajo",
  "luggage": "equipaje",
  "lunch": "almuerzo",
  "make": "hacer",
  "man": "hombre",
  "manager": "gerente",
  "maybe": "quizás",
  "medicine": "medicina",
  "meet": "conocer",
  "meeting": "reunión",
  "milk": "leche",
  "money": "dinero",
  "moon": "luna",
  "morning": "mañana",
  "most": "la mayoría",
  "mother": "madre",
  "mountain": "montaña",
  "mouse": "ratón",
  "mouth": "boca",
  "move": "mover",
  "name": "nombre",
  "near": "cerca",
  "need": "necesitar",
  "network": "red",
  "never": "nunca",
  "new": "nuevo",
  "next": "siguiente",
  "nice": "agradable",
  "no": "no",
  "nobody": "nadie",
  "nose": "nariz",
  "nothing": "nada",
  "now": "ahora",
  "ocean": "océano",
  "office": "oficina",
  "often": "a menudo",
  "okay": "vale",
  "old": "viejo",
  "only": "solo",
  "opposite": "opuesto",
  "orange": "naranja",
  "outside": "fuera",
  "pain": "dolor",
  "passport": "pasaporte",
  "password": "contraseña",
  "pay": "pagar",
  "phone": "teléfono",
  "pizza": "pizza",
  "play": "jugar",
  "please": "por favor",
  "poor": "pobre",
  "previous": "anterior",
  "quiet": "tranquilo",
  "rain": "lluvia",
  "read": "leer",
  "ready": "listo",
  "really": "realmente",
  "rice": "arroz",
  "rich": "rico",
  "river": "río",
  "road": "carretera",
  "run": "correr",
  "sad": "triste",
  "salad": "ensalada",
  "salary": "salario",
  "same": "mismo",
  "say": "decir",
  "screen": "pantalla",
  "see": "ver",
  "see you": "nos vemos",
  "server": "servidor",
  "short": "corto",
  "show": "mostrar",
  "sick": "enfermo",
  "similar": "similar",
  "sister": "hermana",
  "sit": "sentarse",
  "sky": "cielo",
  "sleep": "dormir",
  "slow": "lento",
  "small": "pequeño",
  "snow": "nieve",
  "soft": "suave",
  "software": "software",
  "some": "algunos",
  "someone": "alguien",
  "something": "algo",
  "sometimes": "a veces",
  "somewhere": "en algún lugar",
  "son": "hijo",
  "soon": "pronto",
  "sorry": "lo siento",
  "soup": "sopa",
  "stand": "levantarse",
  "star": "estrella",
  "start": "empezar",
  "still": "todavía",
  "street": "calle",
  "strong": "fuerte",
  "sun": "sol",
  "sure": "seguro",
  "take": "tomar",
  "talk": "hablar",
  "taxi": "taxi",
  "tea": "té",
  "team": "equipo",
  "tell": "decir",
  "thanks": "gracias",
  "that": "eso",
  "there": "allí",
  "these": "estos",
  "think": "pensar",
  "this": "esto",
  "those": "aquellos",
  "ticket": "boleto",
  "tiger": "tigre",
  "today": "hoy",
  "tomorrow": "mañana",
  "too": "demasiado",
  "town": "pueblo",
  "train": "tren",
  "tree": "árbol",
  "try": "intentar",
  "ugly": "feo",
  "upload": "subir",
  "use": "usar",
  "very": "muy",
  "want": "querer",
  "water": "agua",
  "weak": "débil",
  "website": "sitio web",
  "welcome": "bienvenido",
  "what": "qué",
  "when": "cuándo",
  "where": "dónde",
  "who": "quién",
  "why": "por qué",
  "wife": "esposa",
  "wind": "viento",
  "wolf": "lobo",
  "woman": "mujer",
  "work": "trabajar",
  "write": "escribir",
  "yes": "sí",
  "yesterday": "ayer",
  "yet": "aún",
  "young": "joven",
};

export const WORD_CATEGORIES = [
  { id: "greetings_and_basics", name: "Greetings & Basics" },
  { id: "technology", name: "Technology" },
  { id: "travel_and_places", name: "Travel & Places" },
  { id: "food_and_drinks", name: "Food & Drinks" },
  { id: "work_and_business", name: "Work & Business" },
  { id: "family_and_people", name: "Family & People" },
  { id: "animals_and_nature", name: "Animals & Nature" },
  { id: "verbs_-_actions", name: "Verbs - Actions" },
  { id: "adjectives_-_descriptions", name: "Adjectives - Descriptions" },
  { id: "health_and_body", name: "Health & Body" },
];

export const WORDS = [
  { english: "hello", category: "Greetings & Basics", difficulty: 1, translation: "hola" },
  { english: "goodbye", category: "Greetings & Basics", difficulty: 1, translation: "adiós" },
  { english: "please", category: "Greetings & Basics", difficulty: 1, translation: "por favor" },
  { english: "thanks", category: "Greetings & Basics", difficulty: 1, translation: "gracias" },
  { english: "sorry", category: "Greetings & Basics", difficulty: 1, translation: "lo siento" },
  { english: "yes", category: "Greetings & Basics", difficulty: 1, translation: "sí" },
  { english: "no", category: "Greetings & Basics", difficulty: 1, translation: "no" },
  { english: "maybe", category: "Greetings & Basics", difficulty: 1, translation: "quizás" },
  { english: "welcome", category: "Greetings & Basics", difficulty: 1, translation: "bienvenido" },
  { english: "friend", category: "Greetings & Basics", difficulty: 1, translation: "amigo" },
  { english: "good morning", category: "Greetings & Basics", difficulty: 2, translation: "buenos días" },
  { english: "good night", category: "Greetings & Basics", difficulty: 2, translation: "buenas noches" },
  { english: "how are you", category: "Greetings & Basics", difficulty: 2, translation: "cómo estás" },
  { english: "fine", category: "Greetings & Basics", difficulty: 1, translation: "bien" },
  { english: "name", category: "Greetings & Basics", difficulty: 1, translation: "nombre" },
  { english: "meet", category: "Greetings & Basics", difficulty: 1, translation: "conocer" },
  { english: "nice", category: "Greetings & Basics", difficulty: 1, translation: "agradable" },
  { english: "later", category: "Greetings & Basics", difficulty: 1, translation: "después" },
  { english: "see you", category: "Greetings & Basics", difficulty: 2, translation: "nos vemos" },
  { english: "excuse me", category: "Greetings & Basics", difficulty: 2, translation: "disculpe" },
  { english: "morning", category: "Greetings & Basics", difficulty: 1, translation: "mañana" },
  { english: "afternoon", category: "Greetings & Basics", difficulty: 1, translation: "tarde" },
  { english: "evening", category: "Greetings & Basics", difficulty: 1, translation: "noche" },
  { english: "today", category: "Greetings & Basics", difficulty: 1, translation: "hoy" },
  { english: "tomorrow", category: "Greetings & Basics", difficulty: 1, translation: "mañana" },
  { english: "yesterday", category: "Greetings & Basics", difficulty: 1, translation: "ayer" },
  { english: "now", category: "Greetings & Basics", difficulty: 1, translation: "ahora" },
  { english: "soon", category: "Greetings & Basics", difficulty: 1, translation: "pronto" },
  { english: "never", category: "Greetings & Basics", difficulty: 1, translation: "nunca" },
  { english: "always", category: "Greetings & Basics", difficulty: 1, translation: "siempre" },
  { english: "sometimes", category: "Greetings & Basics", difficulty: 1, translation: "a veces" },
  { english: "often", category: "Greetings & Basics", difficulty: 1, translation: "a menudo" },
  { english: "again", category: "Greetings & Basics", difficulty: 1, translation: "otra vez" },
  { english: "ready", category: "Greetings & Basics", difficulty: 1, translation: "listo" },
  { english: "okay", category: "Greetings & Basics", difficulty: 1, translation: "vale" },
  { english: "alright", category: "Greetings & Basics", difficulty: 1, translation: "bien" },
  { english: "sure", category: "Greetings & Basics", difficulty: 1, translation: "seguro" },
  { english: "really", category: "Greetings & Basics", difficulty: 1, translation: "realmente" },
  { english: "absolutely", category: "Greetings & Basics", difficulty: 1, translation: "absolutamente" },
  { english: "exactly", category: "Greetings & Basics", difficulty: 1, translation: "exactamente" },
  { english: "here", category: "Greetings & Basics", difficulty: 1, translation: "aquí" },
  { english: "there", category: "Greetings & Basics", difficulty: 1, translation: "allí" },
  { english: "everywhere", category: "Greetings & Basics", difficulty: 1, translation: "en todas partes" },
  { english: "somewhere", category: "Greetings & Basics", difficulty: 1, translation: "en algún lugar" },
  { english: "anywhere", category: "Greetings & Basics", difficulty: 1, translation: "dondequiera" },
  { english: "nowhere", category: "Greetings & Basics", difficulty: 1, translation: "en ninguna parte" },
  { english: "inside", category: "Greetings & Basics", difficulty: 1, translation: "dentro" },
  { english: "outside", category: "Greetings & Basics", difficulty: 1, translation: "fuera" },
  { english: "near", category: "Greetings & Basics", difficulty: 1, translation: "cerca" },
  { english: "far", category: "Greetings & Basics", difficulty: 1, translation: "lejos" },
  { english: "this", category: "Greetings & Basics", difficulty: 1, translation: "esto" },
  { english: "that", category: "Greetings & Basics", difficulty: 1, translation: "eso" },
  { english: "these", category: "Greetings & Basics", difficulty: 1, translation: "estos" },
  { english: "those", category: "Greetings & Basics", difficulty: 1, translation: "aquellos" },
  { english: "something", category: "Greetings & Basics", difficulty: 1, translation: "algo" },
  { english: "nothing", category: "Greetings & Basics", difficulty: 1, translation: "nada" },
  { english: "everything", category: "Greetings & Basics", difficulty: 1, translation: "todo" },
  { english: "someone", category: "Greetings & Basics", difficulty: 1, translation: "alguien" },
  { english: "anyone", category: "Greetings & Basics", difficulty: 1, translation: "cualquiera" },
  { english: "nobody", category: "Greetings & Basics", difficulty: 1, translation: "nadie" },
  { english: "who", category: "Greetings & Basics", difficulty: 1, translation: "quién" },
  { english: "what", category: "Greetings & Basics", difficulty: 1, translation: "qué" },
  { english: "where", category: "Greetings & Basics", difficulty: 1, translation: "dónde" },
  { english: "when", category: "Greetings & Basics", difficulty: 1, translation: "cuándo" },
  { english: "why", category: "Greetings & Basics", difficulty: 1, translation: "por qué" },
  { english: "how", category: "Greetings & Basics", difficulty: 1, translation: "cómo" },
  { english: "which", category: "Greetings & Basics", difficulty: 1, translation: "cual" },
  { english: "whose", category: "Greetings & Basics", difficulty: 1, translation: "tiene" },
  { english: "whom", category: "Greetings & Basics", difficulty: 1, translation: "a quién" },
  { english: "whatever", category: "Greetings & Basics", difficulty: 1, translation: "cualquier" },
  { english: "also", category: "Greetings & Basics", difficulty: 1, translation: "también" },
  { english: "only", category: "Greetings & Basics", difficulty: 1, translation: "solo" },
  { english: "just", category: "Greetings & Basics", difficulty: 1, translation: "solo" },
  { english: "still", category: "Greetings & Basics", difficulty: 1, translation: "todavía" },
  { english: "yet", category: "Greetings & Basics", difficulty: 1, translation: "aún" },
  { english: "already", category: "Greetings & Basics", difficulty: 1, translation: "ya" },
  { english: "almost", category: "Greetings & Basics", difficulty: 1, translation: "casi" },
  { english: "enough", category: "Greetings & Basics", difficulty: 1, translation: "suficiente" },
  { english: "too", category: "Greetings & Basics", difficulty: 1, translation: "demasiado" },
  { english: "very", category: "Greetings & Basics", difficulty: 1, translation: "muy" },
  { english: "really", category: "Greetings & Basics", difficulty: 1, translation: "realmente" },
  { english: "quite", category: "Greetings & Basics", difficulty: 1, translation: "bastante" },
  { english: "rather", category: "Greetings & Basics", difficulty: 1, translation: "más bien" },
  { english: "hardly", category: "Greetings & Basics", difficulty: 1, translation: "apenas" },
  { english: "barely", category: "Greetings & Basics", difficulty: 1, translation: "apenas" },
  { english: "nearly", category: "Greetings & Basics", difficulty: 1, translation: "casi" },
  { english: "completely", category: "Greetings & Basics", difficulty: 1, translation: "Para" },
  { english: "totally", category: "Greetings & Basics", difficulty: 1, translation: "totalmente" },
  { english: "fully", category: "Greetings & Basics", difficulty: 1, translation: "hacia atrás." },
  { english: "partially", category: "Greetings & Basics", difficulty: 1, translation: "parcialmente" },
  { english: "first", category: "Greetings & Basics", difficulty: 1, translation: "primero" },
  { english: "last", category: "Greetings & Basics", difficulty: 1, translation: "último" },
  { english: "next", category: "Greetings & Basics", difficulty: 1, translation: "siguiente" },
  { english: "previous", category: "Greetings & Basics", difficulty: 1, translation: "anterior" },
  { english: "final", category: "Greetings & Basics", difficulty: 1, translation: null },
  { english: "second", category: "Greetings & Basics", difficulty: 1, translation: "segundo" },
  { english: "third", category: "Greetings & Basics", difficulty: 1, translation: "tercero" },
  { english: "middle", category: "Greetings & Basics", difficulty: 1, translation: "medio" },
  { english: "beginning", category: "Greetings & Basics", difficulty: 1, translation: "principio" },
  { english: "end", category: "Greetings & Basics", difficulty: 1, translation: "fin" },
  { english: "same", category: "Greetings & Basics", difficulty: 1, translation: "mismo" },
  { english: "different", category: "Greetings & Basics", difficulty: 1, translation: "diferente" },
  { english: "similar", category: "Greetings & Basics", difficulty: 1, translation: "similar" },
  { english: "opposite", category: "Greetings & Basics", difficulty: 1, translation: "opuesto" },
  { english: "another", category: "Greetings & Basics", difficulty: 1, translation: "otro" },
  { english: "each", category: "Greetings & Basics", difficulty: 1, translation: "cada" },
  { english: "every", category: "Greetings & Basics", difficulty: 1, translation: "cada" },
  { english: "all", category: "Greetings & Basics", difficulty: 1, translation: "todo" },
  { english: "most", category: "Greetings & Basics", difficulty: 1, translation: "la mayoría" },
  { english: "some", category: "Greetings & Basics", difficulty: 1, translation: "algunos" },
  { english: "computer", category: "Technology", difficulty: 1, translation: "computadora" },
  { english: "phone", category: "Technology", difficulty: 1, translation: "teléfono" },
  { english: "screen", category: "Technology", difficulty: 1, translation: "pantalla" },
  { english: "keyboard", category: "Technology", difficulty: 1, translation: "teclado" },
  { english: "mouse", category: "Technology", difficulty: 1, translation: "ratón" },
  { english: "internet", category: "Technology", difficulty: 1, translation: "internet" },
  { english: "website", category: "Technology", difficulty: 1, translation: "sitio web" },
  { english: "email", category: "Technology", difficulty: 1, translation: "correo electrónico" },
  { english: "password", category: "Technology", difficulty: 1, translation: "contraseña" },
  { english: "download", category: "Technology", difficulty: 1, translation: "descargar" },
  { english: "upload", category: "Technology", difficulty: 1, translation: "subir" },
  { english: "software", category: "Technology", difficulty: 1, translation: "software" },
  { english: "hardware", category: "Technology", difficulty: 1, translation: null },
  { english: "network", category: "Technology", difficulty: 1, translation: "red" },
  { english: "server", category: "Technology", difficulty: 1, translation: "servidor" },
  { english: "database", category: "Technology", difficulty: 1, translation: "base de datos" },
  { english: "code", category: "Technology", difficulty: 1, translation: "código" },
  { english: "program", category: "Technology", difficulty: 1, translation: "pérdida de peso" },
  { english: "application", category: "Technology", difficulty: 1, translation: "aplicación" },
  { english: "file", category: "Technology", difficulty: 1, translation: "archivo" },
  { english: "folder", category: "Technology", difficulty: 1, translation: "carpeta" },
  { english: "cloud", category: "Technology", difficulty: 1, translation: "nube" },
  { english: "data", category: "Technology", difficulty: 1, translation: "datos" },
  { english: "cable", category: "Technology", difficulty: 1, translation: null },
  { english: "charger", category: "Technology", difficulty: 1, translation: "cargador" },
  { english: "battery", category: "Technology", difficulty: 1, translation: "batería" },
  { english: "printer", category: "Technology", difficulty: 1, translation: "Impresora" },
  { english: "camera", category: "Technology", difficulty: 1, translation: "cámara" },
  { english: "microphone", category: "Technology", difficulty: 1, translation: "micrófono" },
  { english: "speaker", category: "Technology", difficulty: 1, translation: "altavoz" },
  { english: "headphones", category: "Technology", difficulty: 1, translation: "auriculares" },
  { english: "bluetooth", category: "Technology", difficulty: 1, translation: null },
  { english: "wifi", category: "Technology", difficulty: 1, translation: null },
  { english: "signal", category: "Technology", difficulty: 1, translation: "reactivos" },
  { english: "router", category: "Technology", difficulty: 1, translation: null },
  { english: "modem", category: "Technology", difficulty: 1, translation: "módem" },
  { english: "cable", category: "Technology", difficulty: 1, translation: null },
  { english: "display", category: "Technology", difficulty: 1, translation: "pantalla" },
  { english: "processor", category: "Technology", difficulty: 1, translation: "procesador" },
  { english: "memory", category: "Technology", difficulty: 1, translation: "memoria" },
  { english: "storage", category: "Technology", difficulty: 1, translation: "almacenamiento" },
  { english: "backup", category: "Technology", difficulty: 1, translation: "respaldo" },
  { english: "update", category: "Technology", difficulty: 1, translation: "actualización" },
  { english: "install", category: "Technology", difficulty: 1, translation: "instalar" },
  { english: "delete", category: "Technology", difficulty: 1, translation: "borrar" },
  { english: "copy", category: "Technology", difficulty: 1, translation: "copia" },
  { english: "paste", category: "Technology", difficulty: 1, translation: "pegar" },
  { english: "search", category: "Technology", difficulty: 1, translation: "buscar" },
  { english: "login", category: "Technology", difficulty: 1, translation: "iniciar sesión" },
  { english: "logout", category: "Technology", difficulty: 1, translation: "cerrar sesión" },
  { english: "account", category: "Technology", difficulty: 1, translation: "cuenta" },
  { english: "profile", category: "Technology", difficulty: 1, translation: "perfil" },
  { english: "settings", category: "Technology", difficulty: 1, translation: "ajustes" },
  { english: "notification", category: "Technology", difficulty: 1, translation: "push" },
  { english: "message", category: "Technology", difficulty: 1, translation: "Mensaje" },
  { english: "chat", category: "Technology", difficulty: 1, translation: null },
  { english: "video call", category: "Technology", difficulty: 2, translation: "envíame una muestra de tu sensualidad" },
  { english: "conference", category: "Technology", difficulty: 1, translation: "conferencia" },
  { english: "stream", category: "Technology", difficulty: 1, translation: ">" },
  { english: "podcast", category: "Technology", difficulty: 1, translation: null },
  { english: "social media", category: "Technology", difficulty: 2, translation: "redes sociales" },
  { english: "blog", category: "Technology", difficulty: 1, translation: null },
  { english: "forum", category: "Technology", difficulty: 1, translation: null },
  { english: "newsletter", category: "Technology", difficulty: 1, translation: "boletín" },
  { english: "subscription", category: "Technology", difficulty: 1, translation: "Suscripción" },
  { english: "spam", category: "Technology", difficulty: 1, translation: null },
  { english: "filter", category: "Technology", difficulty: 1, translation: "filtro" },
  { english: "security", category: "Technology", difficulty: 1, translation: "seguridad internacionales" },
  { english: "virus", category: "Technology", difficulty: 1, translation: null },
  { english: "firewall", category: "Technology", difficulty: 1, translation: "Firewall" },
  { english: "browser", category: "Technology", difficulty: 1, translation: "navegador" },
  { english: "tab", category: "Technology", difficulty: 1, translation: "pestaña" },
  { english: "bookmark", category: "Technology", difficulty: 1, translation: "marcador" },
  { english: "history", category: "Technology", difficulty: 1, translation: "historial" },
  { english: "cache", category: "Technology", difficulty: 1, translation: "caché" },
  { english: "cookie", category: "Technology", difficulty: 1, translation: "de cookies" },
  { english: "plugin", category: "Technology", difficulty: 1, translation: null },
  { english: "extension", category: "Technology", difficulty: 1, translation: null },
  { english: "toolbar", category: "Technology", difficulty: 1, translation: "barra de herramientas" },
  { english: "dashboard", category: "Technology", difficulty: 1, translation: "panel de control" },
  { english: "algorithm", category: "Technology", difficulty: 1, translation: "algoritmo" },
  { english: "encryption", category: "Technology", difficulty: 1, translation: "encriptado" },
  { english: "protocol", category: "Technology", difficulty: 1, translation: "protocolo" },
  { english: "interface", category: "Technology", difficulty: 1, translation: "interfaz" },
  { english: "platform", category: "Technology", difficulty: 1, translation: "de pagos" },
  { english: "framework", category: "Technology", difficulty: 1, translation: "marco" },
  { english: "library", category: "Technology", difficulty: 1, translation: "biblioteca" },
  { english: "syntax", category: "Technology", difficulty: 1, translation: "sintaxis" },
  { english: "debug", category: "Technology", difficulty: 1, translation: "depurar" },
  { english: "compile", category: "Technology", difficulty: 1, translation: "compilar" },
  { english: "virtual", category: "Technology", difficulty: 1, translation: null },
  { english: "remote", category: "Technology", difficulty: 1, translation: "remoto" },
  { english: "digital", category: "Technology", difficulty: 1, translation: null },
  { english: "analog", category: "Technology", difficulty: 1, translation: "analógica(o)" },
  { english: "wireless", category: "Technology", difficulty: 1, translation: "inalámbrico/sin hilos" },
  { english: "smart", category: "Technology", difficulty: 1, translation: null },
  { english: "automatic", category: "Technology", difficulty: 1, translation: "automático" },
  { english: "manual", category: "Technology", difficulty: 1, translation: null },
  { english: "portable", category: "Technology", difficulty: 1, translation: "portátil" },
  { english: "wearable", category: "Technology", difficulty: 1, translation: "ponible" },
  { english: "airport", category: "Travel & Places", difficulty: 1, translation: "aeropuerto" },
  { english: "hotel", category: "Travel & Places", difficulty: 1, translation: "hotel" },
  { english: "ticket", category: "Travel & Places", difficulty: 1, translation: "boleto" },
  { english: "passport", category: "Travel & Places", difficulty: 1, translation: "pasaporte" },
  { english: "luggage", category: "Travel & Places", difficulty: 1, translation: "equipaje" },
  { english: "flight", category: "Travel & Places", difficulty: 1, translation: "vuelo" },
  { english: "train", category: "Travel & Places", difficulty: 1, translation: "tren" },
  { english: "bus", category: "Travel & Places", difficulty: 1, translation: "autobús" },
  { english: "taxi", category: "Travel & Places", difficulty: 1, translation: "taxi" },
  { english: "subway", category: "Travel & Places", difficulty: 1, translation: "metro" },
  { english: "station", category: "Travel & Places", difficulty: 1, translation: "estación" },
  { english: "terminal", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "gate", category: "Travel & Places", difficulty: 1, translation: "limitación" },
  { english: "boarding", category: "Travel & Places", difficulty: 1, translation: "de internado" },
  { english: "arrival", category: "Travel & Places", difficulty: 1, translation: "llegada" },
  { english: "departure", category: "Travel & Places", difficulty: 1, translation: "salida" },
  { english: "destination", category: "Travel & Places", difficulty: 1, translation: "destino" },
  { english: "journey", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "trip", category: "Travel & Places", difficulty: 1, translation: "completo" },
  { english: "vacation", category: "Travel & Places", difficulty: 1, translation: "vacacional" },
  { english: "beach", category: "Travel & Places", difficulty: 1, translation: "playa" },
  { english: "mountain", category: "Travel & Places", difficulty: 1, translation: "montaña" },
  { english: "river", category: "Travel & Places", difficulty: 1, translation: "río" },
  { english: "ocean", category: "Travel & Places", difficulty: 1, translation: "océano" },
  { english: "forest", category: "Travel & Places", difficulty: 1, translation: "bosque" },
  { english: "desert", category: "Travel & Places", difficulty: 1, translation: "desierto" },
  { english: "island", category: "Travel & Places", difficulty: 1, translation: "isla" },
  { english: "city", category: "Travel & Places", difficulty: 1, translation: "ciudad" },
  { english: "town", category: "Travel & Places", difficulty: 1, translation: "pueblo" },
  { english: "village", category: "Travel & Places", difficulty: 1, translation: "la aldea" },
  { english: "street", category: "Travel & Places", difficulty: 1, translation: "calle" },
  { english: "road", category: "Travel & Places", difficulty: 1, translation: "carretera" },
  { english: "highway", category: "Travel & Places", difficulty: 1, translation: "carril rápido" },
  { english: "bridge", category: "Travel & Places", difficulty: 1, translation: "puente" },
  { english: "tunnel", category: "Travel & Places", difficulty: 1, translation: "túnel" },
  { english: "corner", category: "Travel & Places", difficulty: 1, translation: "Corner" },
  { english: "block", category: "Travel & Places", difficulty: 1, translation: "cuadra" },
  { english: "square", category: "Travel & Places", difficulty: 1, translation: "cuadrado" },
  { english: "park", category: "Travel & Places", difficulty: 1, translation: "parque" },
  { english: "garden", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "museum", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "restaurant", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "cafe", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "shop", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "market", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "mall", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "pharmacy", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "hospital", category: "Travel & Places", difficulty: 1, translation: "hospital" },
  { english: "bank", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "police", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "map", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "direction", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "north", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "south", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "east", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "west", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "left", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "right", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "straight", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "turn", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "entrance", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "exit", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "elevator", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "stairs", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "floor", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "room", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "hall", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "lobby", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "reception", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "check-in", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "reservation", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "confirmation", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "cancel", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "delay", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "schedule", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "timetable", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "route", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "transfer", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "stopover", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "layover", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "sightseeing", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "tour", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "guide", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "tourist", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "local", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "foreign", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "abroad", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "overseas", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "border", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "customs", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "visa", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "currency", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "exchange", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "receipt", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "insurance", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "emergency", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "embassy", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "consulate", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "translate", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "phrase", category: "Travel & Places", difficulty: 1, translation: null },
  { english: "water", category: "Food & Drinks", difficulty: 1, translation: "agua" },
  { english: "coffee", category: "Food & Drinks", difficulty: 1, translation: "café" },
  { english: "tea", category: "Food & Drinks", difficulty: 1, translation: "té" },
  { english: "milk", category: "Food & Drinks", difficulty: 1, translation: "leche" },
  { english: "juice", category: "Food & Drinks", difficulty: 1, translation: "jugo" },
  { english: "soda", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "beer", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "wine", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "smoothie", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "milkshake", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "bread", category: "Food & Drinks", difficulty: 1, translation: "pan" },
  { english: "rice", category: "Food & Drinks", difficulty: 1, translation: "arroz" },
  { english: "pasta", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "noodles", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "pizza", category: "Food & Drinks", difficulty: 1, translation: "pizza" },
  { english: "burger", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "sandwich", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "soup", category: "Food & Drinks", difficulty: 1, translation: "sopa" },
  { english: "salad", category: "Food & Drinks", difficulty: 1, translation: "ensalada" },
  { english: "steak", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "chicken", category: "Food & Drinks", difficulty: 1, translation: "pollo" },
  { english: "fish", category: "Food & Drinks", difficulty: 1, translation: "pez" },
  { english: "shrimp", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "egg", category: "Food & Drinks", difficulty: 1, translation: "huevo" },
  { english: "cheese", category: "Food & Drinks", difficulty: 1, translation: "queso" },
  { english: "butter", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "cream", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "yogurt", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "ice cream", category: "Food & Drinks", difficulty: 2, translation: null },
  { english: "cake", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "chocolate", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "cookie", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "candy", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "fruit", category: "Food & Drinks", difficulty: 1, translation: "fruta" },
  { english: "apple", category: "Food & Drinks", difficulty: 1, translation: "manzana" },
  { english: "banana", category: "Food & Drinks", difficulty: 1, translation: "plátano" },
  { english: "orange", category: "Food & Drinks", difficulty: 1, translation: "naranja" },
  { english: "grape", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "strawberry", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "lemon", category: "Food & Drinks", difficulty: 1, translation: "limón" },
  { english: "vegetable", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "potato", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "tomato", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "carrot", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "onion", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "garlic", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "pepper", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "lettuce", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "broccoli", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "corn", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "breakfast", category: "Food & Drinks", difficulty: 1, translation: "desayuno" },
  { english: "lunch", category: "Food & Drinks", difficulty: 1, translation: "almuerzo" },
  { english: "dinner", category: "Food & Drinks", difficulty: 1, translation: "cena" },
  { english: "snack", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "dessert", category: "Food & Drinks", difficulty: 1, translation: "postre" },
  { english: "appetizer", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "main course", category: "Food & Drinks", difficulty: 2, translation: null },
  { english: "side dish", category: "Food & Drinks", difficulty: 2, translation: null },
  { english: "buffet", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "menu", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "order", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "serve", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "cook", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "bake", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "fry", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "boil", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "grill", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "roast", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "steam", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "toast", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "spicy", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "sweet", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "salty", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "sour", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "bitter", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "fresh", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "delicious", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "tasty", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "hot", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "cold", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "plate", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "bowl", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "cup", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "glass", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "fork", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "knife", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "spoon", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "napkin", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "straw", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "bottle", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "hungry", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "thirsty", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "full", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "meal", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "recipe", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "ingredient", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "sauce", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "spice", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "herb", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "flavor", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "organic", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "vegetarian", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "vegan", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "gluten", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "allergy", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "diet", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "calorie", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "portion", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "leftover", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "takeout", category: "Food & Drinks", difficulty: 1, translation: null },
  { english: "job", category: "Work & Business", difficulty: 1, translation: "trabajo" },
  { english: "work", category: "Work & Business", difficulty: 1, translation: "trabajar" },
  { english: "office", category: "Work & Business", difficulty: 1, translation: "oficina" },
  { english: "meeting", category: "Work & Business", difficulty: 1, translation: "reunión" },
  { english: "project", category: "Work & Business", difficulty: 1, translation: null },
  { english: "deadline", category: "Work & Business", difficulty: 1, translation: null },
  { english: "report", category: "Work & Business", difficulty: 1, translation: null },
  { english: "presentation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "client", category: "Work & Business", difficulty: 1, translation: null },
  { english: "customer", category: "Work & Business", difficulty: 1, translation: null },
  { english: "colleague", category: "Work & Business", difficulty: 1, translation: null },
  { english: "boss", category: "Work & Business", difficulty: 1, translation: "jefe" },
  { english: "manager", category: "Work & Business", difficulty: 1, translation: "gerente" },
  { english: "team", category: "Work & Business", difficulty: 1, translation: "equipo" },
  { english: "department", category: "Work & Business", difficulty: 1, translation: null },
  { english: "company", category: "Work & Business", difficulty: 1, translation: "empresa" },
  { english: "corporation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "startup", category: "Work & Business", difficulty: 1, translation: null },
  { english: "business", category: "Work & Business", difficulty: 1, translation: null },
  { english: "enterprise", category: "Work & Business", difficulty: 1, translation: null },
  { english: "salary", category: "Work & Business", difficulty: 1, translation: "salario" },
  { english: "income", category: "Work & Business", difficulty: 1, translation: null },
  { english: "budget", category: "Work & Business", difficulty: 1, translation: null },
  { english: "expense", category: "Work & Business", difficulty: 1, translation: null },
  { english: "profit", category: "Work & Business", difficulty: 1, translation: null },
  { english: "loss", category: "Work & Business", difficulty: 1, translation: null },
  { english: "investment", category: "Work & Business", difficulty: 1, translation: null },
  { english: "revenue", category: "Work & Business", difficulty: 1, translation: null },
  { english: "tax", category: "Work & Business", difficulty: 1, translation: null },
  { english: "invoice", category: "Work & Business", difficulty: 1, translation: null },
  { english: "contract", category: "Work & Business", difficulty: 1, translation: "contrato" },
  { english: "agreement", category: "Work & Business", difficulty: 1, translation: null },
  { english: "negotiation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "proposal", category: "Work & Business", difficulty: 1, translation: null },
  { english: "offer", category: "Work & Business", difficulty: 1, translation: null },
  { english: "deal", category: "Work & Business", difficulty: 1, translation: null },
  { english: "partnership", category: "Work & Business", difficulty: 1, translation: null },
  { english: "merger", category: "Work & Business", difficulty: 1, translation: null },
  { english: "acquisition", category: "Work & Business", difficulty: 1, translation: null },
  { english: "strategy", category: "Work & Business", difficulty: 1, translation: null },
  { english: "goal", category: "Work & Business", difficulty: 1, translation: null },
  { english: "objective", category: "Work & Business", difficulty: 1, translation: null },
  { english: "target", category: "Work & Business", difficulty: 1, translation: null },
  { english: "result", category: "Work & Business", difficulty: 1, translation: null },
  { english: "performance", category: "Work & Business", difficulty: 1, translation: null },
  { english: "evaluation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "feedback", category: "Work & Business", difficulty: 1, translation: null },
  { english: "improvement", category: "Work & Business", difficulty: 1, translation: null },
  { english: "growth", category: "Work & Business", difficulty: 1, translation: null },
  { english: "development", category: "Work & Business", difficulty: 1, translation: null },
  { english: "skill", category: "Work & Business", difficulty: 1, translation: null },
  { english: "experience", category: "Work & Business", difficulty: 1, translation: null },
  { english: "resume", category: "Work & Business", difficulty: 1, translation: null },
  { english: "interview", category: "Work & Business", difficulty: 1, translation: null },
  { english: "hire", category: "Work & Business", difficulty: 1, translation: null },
  { english: "fire", category: "Work & Business", difficulty: 1, translation: null },
  { english: "promotion", category: "Work & Business", difficulty: 1, translation: null },
  { english: "raise", category: "Work & Business", difficulty: 1, translation: null },
  { english: "bonus", category: "Work & Business", difficulty: 1, translation: null },
  { english: "benefits", category: "Work & Business", difficulty: 1, translation: null },
  { english: "schedule", category: "Work & Business", difficulty: 1, translation: null },
  { english: "shift", category: "Work & Business", difficulty: 1, translation: null },
  { english: "overtime", category: "Work & Business", difficulty: 1, translation: null },
  { english: "break", category: "Work & Business", difficulty: 1, translation: null },
  { english: "lunch", category: "Work & Business", difficulty: 1, translation: "almuerzo" },
  { english: "vacation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "leave", category: "Work & Business", difficulty: 1, translation: null },
  { english: "holiday", category: "Work & Business", difficulty: 1, translation: null },
  { english: "remote", category: "Work & Business", difficulty: 1, translation: null },
  { english: "hybrid", category: "Work & Business", difficulty: 1, translation: null },
  { english: "email", category: "Work & Business", difficulty: 1, translation: "correo electrónico" },
  { english: "call", category: "Work & Business", difficulty: 1, translation: "llamar" },
  { english: "conference", category: "Work & Business", difficulty: 1, translation: null },
  { english: "presentation", category: "Work & Business", difficulty: 1, translation: null },
  { english: "spreadsheet", category: "Work & Business", difficulty: 1, translation: null },
  { english: "document", category: "Work & Business", difficulty: 1, translation: null },
  { english: "slide", category: "Work & Business", difficulty: 1, translation: null },
  { english: "agenda", category: "Work & Business", difficulty: 1, translation: null },
  { english: "minutes", category: "Work & Business", difficulty: 1, translation: null },
  { english: "action", category: "Work & Business", difficulty: 1, translation: null },
  { english: "task", category: "Work & Business", difficulty: 1, translation: null },
  { english: "priority", category: "Work & Business", difficulty: 1, translation: null },
  { english: "progress", category: "Work & Business", difficulty: 1, translation: null },
  { english: "status", category: "Work & Business", difficulty: 1, translation: null },
  { english: "update", category: "Work & Business", difficulty: 1, translation: null },
  { english: "check-in", category: "Work & Business", difficulty: 1, translation: null },
  { english: "follow-up", category: "Work & Business", difficulty: 1, translation: null },
  { english: "review", category: "Work & Business", difficulty: 1, translation: null },
  { english: "approval", category: "Work & Business", difficulty: 1, translation: null },
  { english: "signature", category: "Work & Business", difficulty: 1, translation: null },
  { english: "market", category: "Work & Business", difficulty: 1, translation: null },
  { english: "industry", category: "Work & Business", difficulty: 1, translation: null },
  { english: "competitor", category: "Work & Business", difficulty: 1, translation: null },
  { english: "product", category: "Work & Business", difficulty: 1, translation: null },
  { english: "service", category: "Work & Business", difficulty: 1, translation: null },
  { english: "brand", category: "Work & Business", difficulty: 1, translation: null },
  { english: "marketing", category: "Work & Business", difficulty: 1, translation: null },
  { english: "sales", category: "Work & Business", difficulty: 1, translation: null },
  { english: "support", category: "Work & Business", difficulty: 1, translation: null },
  { english: "quality", category: "Work & Business", difficulty: 1, translation: null },
  { english: "mother", category: "Family & People", difficulty: 1, translation: "madre" },
  { english: "father", category: "Family & People", difficulty: 1, translation: "padre" },
  { english: "parent", category: "Family & People", difficulty: 1, translation: null },
  { english: "child", category: "Family & People", difficulty: 1, translation: "niño" },
  { english: "son", category: "Family & People", difficulty: 1, translation: "hijo" },
  { english: "daughter", category: "Family & People", difficulty: 1, translation: "hija" },
  { english: "brother", category: "Family & People", difficulty: 1, translation: "hermano" },
  { english: "sister", category: "Family & People", difficulty: 1, translation: "hermana" },
  { english: "sibling", category: "Family & People", difficulty: 1, translation: null },
  { english: "baby", category: "Family & People", difficulty: 1, translation: "bebé" },
  { english: "grandmother", category: "Family & People", difficulty: 1, translation: null },
  { english: "grandfather", category: "Family & People", difficulty: 1, translation: null },
  { english: "aunt", category: "Family & People", difficulty: 1, translation: null },
  { english: "uncle", category: "Family & People", difficulty: 1, translation: null },
  { english: "cousin", category: "Family & People", difficulty: 1, translation: null },
  { english: "nephew", category: "Family & People", difficulty: 1, translation: null },
  { english: "niece", category: "Family & People", difficulty: 1, translation: null },
  { english: "husband", category: "Family & People", difficulty: 1, translation: "esposo" },
  { english: "wife", category: "Family & People", difficulty: 1, translation: "esposa" },
  { english: "partner", category: "Family & People", difficulty: 1, translation: null },
  { english: "family", category: "Family & People", difficulty: 1, translation: "familia" },
  { english: "relative", category: "Family & People", difficulty: 1, translation: null },
  { english: "ancestor", category: "Family & People", difficulty: 1, translation: null },
  { english: "descendant", category: "Family & People", difficulty: 1, translation: null },
  { english: "generation", category: "Family & People", difficulty: 1, translation: null },
  { english: "marriage", category: "Family & People", difficulty: 1, translation: null },
  { english: "wedding", category: "Family & People", difficulty: 1, translation: null },
  { english: "divorce", category: "Family & People", difficulty: 1, translation: null },
  { english: "adoption", category: "Family & People", difficulty: 1, translation: null },
  { english: "twins", category: "Family & People", difficulty: 1, translation: null },
  { english: "friend", category: "Family & People", difficulty: 1, translation: "amigo" },
  { english: "neighbor", category: "Family & People", difficulty: 1, translation: null },
  { english: "roommate", category: "Family & People", difficulty: 1, translation: null },
  { english: "classmate", category: "Family & People", difficulty: 1, translation: null },
  { english: "coworker", category: "Family & People", difficulty: 1, translation: null },
  { english: "acquaintance", category: "Family & People", difficulty: 1, translation: null },
  { english: "stranger", category: "Family & People", difficulty: 1, translation: null },
  { english: "guest", category: "Family & People", difficulty: 1, translation: null },
  { english: "host", category: "Family & People", difficulty: 1, translation: null },
  { english: "visitor", category: "Family & People", difficulty: 1, translation: null },
  { english: "man", category: "Family & People", difficulty: 1, translation: "hombre" },
  { english: "woman", category: "Family & People", difficulty: 1, translation: "mujer" },
  { english: "boy", category: "Family & People", difficulty: 1, translation: "niño" },
  { english: "girl", category: "Family & People", difficulty: 1, translation: "niña" },
  { english: "person", category: "Family & People", difficulty: 1, translation: null },
  { english: "people", category: "Family & People", difficulty: 1, translation: null },
  { english: "adult", category: "Family & People", difficulty: 1, translation: null },
  { english: "teenager", category: "Family & People", difficulty: 1, translation: null },
  { english: "kid", category: "Family & People", difficulty: 1, translation: null },
  { english: "senior", category: "Family & People", difficulty: 1, translation: null },
  { english: "name", category: "Family & People", difficulty: 1, translation: "nombre" },
  { english: "age", category: "Family & People", difficulty: 1, translation: null },
  { english: "birthday", category: "Family & People", difficulty: 1, translation: null },
  { english: "birth", category: "Family & People", difficulty: 1, translation: null },
  { english: "death", category: "Family & People", difficulty: 1, translation: null },
  { english: "life", category: "Family & People", difficulty: 1, translation: null },
  { english: "alive", category: "Family & People", difficulty: 1, translation: null },
  { english: "young", category: "Family & People", difficulty: 1, translation: "joven" },
  { english: "old", category: "Family & People", difficulty: 1, translation: "viejo" },
  { english: "middle-aged", category: "Family & People", difficulty: 1, translation: null },
  { english: "tall", category: "Family & People", difficulty: 1, translation: null },
  { english: "short", category: "Family & People", difficulty: 1, translation: "corto" },
  { english: "thin", category: "Family & People", difficulty: 1, translation: null },
  { english: "heavy", category: "Family & People", difficulty: 1, translation: null },
  { english: "beautiful", category: "Family & People", difficulty: 1, translation: "hermoso" },
  { english: "handsome", category: "Family & People", difficulty: 1, translation: null },
  { english: "pretty", category: "Family & People", difficulty: 1, translation: null },
  { english: "ugly", category: "Family & People", difficulty: 1, translation: "feo" },
  { english: "strong", category: "Family & People", difficulty: 1, translation: "fuerte" },
  { english: "weak", category: "Family & People", difficulty: 1, translation: "débil" },
  { english: "kind", category: "Family & People", difficulty: 1, translation: null },
  { english: "mean", category: "Family & People", difficulty: 1, translation: null },
  { english: "friendly", category: "Family & People", difficulty: 1, translation: null },
  { english: "shy", category: "Family & People", difficulty: 1, translation: null },
  { english: "funny", category: "Family & People", difficulty: 1, translation: null },
  { english: "serious", category: "Family & People", difficulty: 1, translation: null },
  { english: "smart", category: "Family & People", difficulty: 1, translation: null },
  { english: "silly", category: "Family & People", difficulty: 1, translation: null },
  { english: "brave", category: "Family & People", difficulty: 1, translation: null },
  { english: "careful", category: "Family & People", difficulty: 1, translation: null },
  { english: "happy", category: "Family & People", difficulty: 1, translation: "feliz" },
  { english: "sad", category: "Family & People", difficulty: 1, translation: "triste" },
  { english: "angry", category: "Family & People", difficulty: 1, translation: null },
  { english: "calm", category: "Family & People", difficulty: 1, translation: null },
  { english: "nervous", category: "Family & People", difficulty: 1, translation: null },
  { english: "excited", category: "Family & People", difficulty: 1, translation: null },
  { english: "bored", category: "Family & People", difficulty: 1, translation: null },
  { english: "tired", category: "Family & People", difficulty: 1, translation: null },
  { english: "proud", category: "Family & People", difficulty: 1, translation: null },
  { english: "jealous", category: "Family & People", difficulty: 1, translation: null },
  { english: "love", category: "Family & People", difficulty: 1, translation: null },
  { english: "hate", category: "Family & People", difficulty: 1, translation: null },
  { english: "trust", category: "Family & People", difficulty: 1, translation: null },
  { english: "respect", category: "Family & People", difficulty: 1, translation: null },
  { english: "admire", category: "Family & People", difficulty: 1, translation: null },
  { english: "envy", category: "Family & People", difficulty: 1, translation: null },
  { english: "forgive", category: "Family & People", difficulty: 1, translation: null },
  { english: "apologize", category: "Family & People", difficulty: 1, translation: null },
  { english: "thank", category: "Family & People", difficulty: 1, translation: null },
  { english: "greet", category: "Family & People", difficulty: 1, translation: null },
  { english: "dog", category: "Animals & Nature", difficulty: 1, translation: "perro" },
  { english: "cat", category: "Animals & Nature", difficulty: 1, translation: "gato" },
  { english: "bird", category: "Animals & Nature", difficulty: 1, translation: "pájaro" },
  { english: "fish", category: "Animals & Nature", difficulty: 1, translation: "pez" },
  { english: "horse", category: "Animals & Nature", difficulty: 1, translation: "caballo" },
  { english: "cow", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "pig", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "sheep", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "goat", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "chicken", category: "Animals & Nature", difficulty: 1, translation: "pollo" },
  { english: "duck", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "rabbit", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "mouse", category: "Animals & Nature", difficulty: 1, translation: "ratón" },
  { english: "rat", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "snake", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "frog", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "turtle", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "whale", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "shark", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "dolphin", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "bear", category: "Animals & Nature", difficulty: 1, translation: "oso" },
  { english: "wolf", category: "Animals & Nature", difficulty: 1, translation: "lobo" },
  { english: "fox", category: "Animals & Nature", difficulty: 1, translation: "zorro" },
  { english: "deer", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "monkey", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "gorilla", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "elephant", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "lion", category: "Animals & Nature", difficulty: 1, translation: "león" },
  { english: "tiger", category: "Animals & Nature", difficulty: 1, translation: "tigre" },
  { english: "zebra", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "eagle", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "owl", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "parrot", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "penguin", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "butterfly", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "bee", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "ant", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "spider", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "mosquito", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "dragonfly", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "tree", category: "Animals & Nature", difficulty: 1, translation: "árbol" },
  { english: "flower", category: "Animals & Nature", difficulty: 1, translation: "flor" },
  { english: "grass", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "leaf", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "root", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "seed", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "fruit", category: "Animals & Nature", difficulty: 1, translation: "fruta" },
  { english: "vegetable", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "plant", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "garden", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "forest", category: "Animals & Nature", difficulty: 1, translation: "bosque" },
  { english: "jungle", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "desert", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "mountain", category: "Animals & Nature", difficulty: 1, translation: "montaña" },
  { english: "valley", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "hill", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "cave", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "volcano", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "waterfall", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "lake", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "sun", category: "Animals & Nature", difficulty: 1, translation: "sol" },
  { english: "moon", category: "Animals & Nature", difficulty: 1, translation: "luna" },
  { english: "star", category: "Animals & Nature", difficulty: 1, translation: "estrella" },
  { english: "planet", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "earth", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "sky", category: "Animals & Nature", difficulty: 1, translation: "cielo" },
  { english: "cloud", category: "Animals & Nature", difficulty: 1, translation: "nube" },
  { english: "rain", category: "Animals & Nature", difficulty: 1, translation: "lluvia" },
  { english: "snow", category: "Animals & Nature", difficulty: 1, translation: "nieve" },
  { english: "wind", category: "Animals & Nature", difficulty: 1, translation: "viento" },
  { english: "storm", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "thunder", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "lightning", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "rainbow", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "flood", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "drought", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "earthquake", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "hurricane", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "tornado", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "tsunami", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "weather", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "climate", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "temperature", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "degree", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "hot", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "warm", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "cool", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "cold", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "freezing", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "humid", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "season", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "spring", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "summer", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "autumn", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "winter", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "day", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "night", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "dawn", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "dusk", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "sunrise", category: "Animals & Nature", difficulty: 1, translation: null },
  { english: "be", category: "Verbs - Actions", difficulty: 1, translation: "ser" },
  { english: "have", category: "Verbs - Actions", difficulty: 1, translation: "tener" },
  { english: "do", category: "Verbs - Actions", difficulty: 1, translation: "hacer" },
  { english: "say", category: "Verbs - Actions", difficulty: 1, translation: "decir" },
  { english: "go", category: "Verbs - Actions", difficulty: 1, translation: "ir" },
  { english: "get", category: "Verbs - Actions", difficulty: 1, translation: "obtener" },
  { english: "make", category: "Verbs - Actions", difficulty: 1, translation: "hacer" },
  { english: "know", category: "Verbs - Actions", difficulty: 1, translation: "saber" },
  { english: "think", category: "Verbs - Actions", difficulty: 1, translation: "pensar" },
  { english: "take", category: "Verbs - Actions", difficulty: 1, translation: "tomar" },
  { english: "see", category: "Verbs - Actions", difficulty: 1, translation: "ver" },
  { english: "come", category: "Verbs - Actions", difficulty: 1, translation: "venir" },
  { english: "want", category: "Verbs - Actions", difficulty: 1, translation: "querer" },
  { english: "look", category: "Verbs - Actions", difficulty: 1, translation: "mirar" },
  { english: "use", category: "Verbs - Actions", difficulty: 1, translation: "usar" },
  { english: "find", category: "Verbs - Actions", difficulty: 1, translation: "encontrar" },
  { english: "give", category: "Verbs - Actions", difficulty: 1, translation: "dar" },
  { english: "tell", category: "Verbs - Actions", difficulty: 1, translation: "decir" },
  { english: "work", category: "Verbs - Actions", difficulty: 1, translation: "trabajar" },
  { english: "call", category: "Verbs - Actions", difficulty: 1, translation: "llamar" },
  { english: "try", category: "Verbs - Actions", difficulty: 1, translation: "intentar" },
  { english: "ask", category: "Verbs - Actions", difficulty: 1, translation: "preguntar" },
  { english: "need", category: "Verbs - Actions", difficulty: 1, translation: "necesitar" },
  { english: "feel", category: "Verbs - Actions", difficulty: 1, translation: "sentir" },
  { english: "become", category: "Verbs - Actions", difficulty: 1, translation: "convertirse" },
  { english: "leave", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "put", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "mean", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "keep", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "let", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "begin", category: "Verbs - Actions", difficulty: 1, translation: "comenzar" },
  { english: "seem", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "help", category: "Verbs - Actions", difficulty: 1, translation: "ayudar" },
  { english: "talk", category: "Verbs - Actions", difficulty: 1, translation: "hablar" },
  { english: "turn", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "start", category: "Verbs - Actions", difficulty: 1, translation: "empezar" },
  { english: "show", category: "Verbs - Actions", difficulty: 1, translation: "mostrar" },
  { english: "hear", category: "Verbs - Actions", difficulty: 1, translation: "oír" },
  { english: "play", category: "Verbs - Actions", difficulty: 1, translation: "jugar" },
  { english: "run", category: "Verbs - Actions", difficulty: 1, translation: "correr" },
  { english: "move", category: "Verbs - Actions", difficulty: 1, translation: "mover" },
  { english: "like", category: "Verbs - Actions", difficulty: 1, translation: "gustar" },
  { english: "live", category: "Verbs - Actions", difficulty: 1, translation: "vivir" },
  { english: "believe", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "hold", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "bring", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "happen", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "write", category: "Verbs - Actions", difficulty: 1, translation: "escribir" },
  { english: "provide", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "sit", category: "Verbs - Actions", difficulty: 1, translation: "sentarse" },
  { english: "stand", category: "Verbs - Actions", difficulty: 1, translation: "levantarse" },
  { english: "lose", category: "Verbs - Actions", difficulty: 1, translation: "perder" },
  { english: "pay", category: "Verbs - Actions", difficulty: 1, translation: "pagar" },
  { english: "meet", category: "Verbs - Actions", difficulty: 1, translation: "conocer" },
  { english: "include", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "continue", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "set", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "learn", category: "Verbs - Actions", difficulty: 1, translation: "aprender" },
  { english: "change", category: "Verbs - Actions", difficulty: 1, translation: "cambiar" },
  { english: "lead", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "understand", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "watch", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "follow", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "stop", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "create", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "speak", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "read", category: "Verbs - Actions", difficulty: 1, translation: "leer" },
  { english: "allow", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "add", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "spend", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "grow", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "open", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "walk", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "win", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "offer", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "remember", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "love", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "consider", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "appear", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "buy", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "wait", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "serve", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "die", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "send", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "expect", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "build", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "stay", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "fall", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "cut", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "reach", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "kill", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "remain", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "suggest", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "raise", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "pass", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "sell", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "require", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "report", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "decide", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "pull", category: "Verbs - Actions", difficulty: 1, translation: null },
  { english: "good", category: "Adjectives - Descriptions", difficulty: 1, translation: "bueno" },
  { english: "bad", category: "Adjectives - Descriptions", difficulty: 1, translation: "malo" },
  { english: "new", category: "Adjectives - Descriptions", difficulty: 1, translation: "nuevo" },
  { english: "old", category: "Adjectives - Descriptions", difficulty: 1, translation: "viejo" },
  { english: "big", category: "Adjectives - Descriptions", difficulty: 1, translation: "grande" },
  { english: "small", category: "Adjectives - Descriptions", difficulty: 1, translation: "pequeño" },
  { english: "large", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "little", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "long", category: "Adjectives - Descriptions", difficulty: 1, translation: "largo" },
  { english: "short", category: "Adjectives - Descriptions", difficulty: 1, translation: "corto" },
  { english: "high", category: "Adjectives - Descriptions", difficulty: 1, translation: "alto" },
  { english: "low", category: "Adjectives - Descriptions", difficulty: 1, translation: "bajo" },
  { english: "wide", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "narrow", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "thick", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "thin", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "deep", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "shallow", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "heavy", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "light", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "fast", category: "Adjectives - Descriptions", difficulty: 1, translation: "rápido" },
  { english: "slow", category: "Adjectives - Descriptions", difficulty: 1, translation: "lento" },
  { english: "quick", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "rapid", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "early", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "late", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "young", category: "Adjectives - Descriptions", difficulty: 1, translation: "joven" },
  { english: "ancient", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "modern", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "traditional", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "rich", category: "Adjectives - Descriptions", difficulty: 1, translation: "rico" },
  { english: "poor", category: "Adjectives - Descriptions", difficulty: 1, translation: "pobre" },
  { english: "expensive", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "cheap", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "clean", category: "Adjectives - Descriptions", difficulty: 1, translation: "limpio" },
  { english: "dirty", category: "Adjectives - Descriptions", difficulty: 1, translation: "sucio" },
  { english: "dry", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "wet", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "hard", category: "Adjectives - Descriptions", difficulty: 1, translation: "duro" },
  { english: "soft", category: "Adjectives - Descriptions", difficulty: 1, translation: "suave" },
  { english: "easy", category: "Adjectives - Descriptions", difficulty: 1, translation: "fácil" },
  { english: "difficult", category: "Adjectives - Descriptions", difficulty: 1, translation: "difícil" },
  { english: "simple", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "complex", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "basic", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "advanced", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "common", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "rare", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "normal", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "strange", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "beautiful", category: "Adjectives - Descriptions", difficulty: 1, translation: "hermoso" },
  { english: "ugly", category: "Adjectives - Descriptions", difficulty: 1, translation: "feo" },
  { english: "pretty", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "plain", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "elegant", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "rough", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "smooth", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "sharp", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "dull", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "flat", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "bright", category: "Adjectives - Descriptions", difficulty: 1, translation: "brillante" },
  { english: "dark", category: "Adjectives - Descriptions", difficulty: 1, translation: "oscuro" },
  { english: "colorful", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "pale", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "shiny", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "dull", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "clear", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "blurry", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "loud", category: "Adjectives - Descriptions", difficulty: 1, translation: "ruidoso" },
  { english: "quiet", category: "Adjectives - Descriptions", difficulty: 1, translation: "tranquilo" },
  { english: "strong", category: "Adjectives - Descriptions", difficulty: 1, translation: "fuerte" },
  { english: "weak", category: "Adjectives - Descriptions", difficulty: 1, translation: "débil" },
  { english: "powerful", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "fragile", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "tough", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "gentle", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "fierce", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "mild", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "wild", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "tame", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "happy", category: "Adjectives - Descriptions", difficulty: 1, translation: "feliz" },
  { english: "sad", category: "Adjectives - Descriptions", difficulty: 1, translation: "triste" },
  { english: "glad", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "upset", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "angry", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "calm", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "brave", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "afraid", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "shy", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "bold", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "wise", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "foolish", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "clever", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "stupid", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "smart", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "dumb", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "kind", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "cruel", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "polite", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "rude", category: "Adjectives - Descriptions", difficulty: 1, translation: null },
  { english: "head", category: "Health & Body", difficulty: 1, translation: "cabeza" },
  { english: "face", category: "Health & Body", difficulty: 1, translation: "cara" },
  { english: "eye", category: "Health & Body", difficulty: 1, translation: "ojo" },
  { english: "ear", category: "Health & Body", difficulty: 1, translation: "oreja" },
  { english: "nose", category: "Health & Body", difficulty: 1, translation: "nariz" },
  { english: "mouth", category: "Health & Body", difficulty: 1, translation: "boca" },
  { english: "lip", category: "Health & Body", difficulty: 1, translation: null },
  { english: "tooth", category: "Health & Body", difficulty: 1, translation: null },
  { english: "tongue", category: "Health & Body", difficulty: 1, translation: null },
  { english: "chin", category: "Health & Body", difficulty: 1, translation: null },
  { english: "neck", category: "Health & Body", difficulty: 1, translation: null },
  { english: "shoulder", category: "Health & Body", difficulty: 1, translation: null },
  { english: "arm", category: "Health & Body", difficulty: 1, translation: null },
  { english: "elbow", category: "Health & Body", difficulty: 1, translation: null },
  { english: "wrist", category: "Health & Body", difficulty: 1, translation: null },
  { english: "hand", category: "Health & Body", difficulty: 1, translation: "mano" },
  { english: "finger", category: "Health & Body", difficulty: 1, translation: null },
  { english: "thumb", category: "Health & Body", difficulty: 1, translation: null },
  { english: "nail", category: "Health & Body", difficulty: 1, translation: null },
  { english: "chest", category: "Health & Body", difficulty: 1, translation: null },
  { english: "back", category: "Health & Body", difficulty: 1, translation: null },
  { english: "spine", category: "Health & Body", difficulty: 1, translation: null },
  { english: "hip", category: "Health & Body", difficulty: 1, translation: null },
  { english: "leg", category: "Health & Body", difficulty: 1, translation: null },
  { english: "knee", category: "Health & Body", difficulty: 1, translation: null },
  { english: "ankle", category: "Health & Body", difficulty: 1, translation: null },
  { english: "foot", category: "Health & Body", difficulty: 1, translation: "pie" },
  { english: "toe", category: "Health & Body", difficulty: 1, translation: null },
  { english: "skin", category: "Health & Body", difficulty: 1, translation: null },
  { english: "bone", category: "Health & Body", difficulty: 1, translation: null },
  { english: "muscle", category: "Health & Body", difficulty: 1, translation: null },
  { english: "heart", category: "Health & Body", difficulty: 1, translation: "corazón" },
  { english: "brain", category: "Health & Body", difficulty: 1, translation: null },
  { english: "lung", category: "Health & Body", difficulty: 1, translation: null },
  { english: "liver", category: "Health & Body", difficulty: 1, translation: null },
  { english: "kidney", category: "Health & Body", difficulty: 1, translation: null },
  { english: "stomach", category: "Health & Body", difficulty: 1, translation: null },
  { english: "blood", category: "Health & Body", difficulty: 1, translation: null },
  { english: "vein", category: "Health & Body", difficulty: 1, translation: null },
  { english: "nerve", category: "Health & Body", difficulty: 1, translation: null },
  { english: "doctor", category: "Health & Body", difficulty: 1, translation: "médico" },
  { english: "nurse", category: "Health & Body", difficulty: 1, translation: null },
  { english: "patient", category: "Health & Body", difficulty: 1, translation: null },
  { english: "hospital", category: "Health & Body", difficulty: 1, translation: "hospital" },
  { english: "clinic", category: "Health & Body", difficulty: 1, translation: null },
  { english: "pharmacy", category: "Health & Body", difficulty: 1, translation: null },
  { english: "medicine", category: "Health & Body", difficulty: 1, translation: "medicina" },
  { english: "pill", category: "Health & Body", difficulty: 1, translation: null },
  { english: "syrup", category: "Health & Body", difficulty: 1, translation: null },
  { english: "injection", category: "Health & Body", difficulty: 1, translation: null },
  { english: "pain", category: "Health & Body", difficulty: 1, translation: "dolor" },
  { english: "ache", category: "Health & Body", difficulty: 1, translation: null },
  { english: "headache", category: "Health & Body", difficulty: 1, translation: null },
  { english: "fever", category: "Health & Body", difficulty: 1, translation: null },
  { english: "cough", category: "Health & Body", difficulty: 1, translation: null },
  { english: "cold", category: "Health & Body", difficulty: 1, translation: null },
  { english: "flu", category: "Health & Body", difficulty: 1, translation: null },
  { english: "allergy", category: "Health & Body", difficulty: 1, translation: null },
  { english: "infection", category: "Health & Body", difficulty: 1, translation: null },
  { english: "wound", category: "Health & Body", difficulty: 1, translation: null },
  { english: "healthy", category: "Health & Body", difficulty: 1, translation: "saludable" },
  { english: "sick", category: "Health & Body", difficulty: 1, translation: "enfermo" },
  { english: "ill", category: "Health & Body", difficulty: 1, translation: null },
  { english: "well", category: "Health & Body", difficulty: 1, translation: null },
  { english: "better", category: "Health & Body", difficulty: 1, translation: null },
  { english: "worse", category: "Health & Body", difficulty: 1, translation: null },
  { english: "tired", category: "Health & Body", difficulty: 1, translation: null },
  { english: "rested", category: "Health & Body", difficulty: 1, translation: null },
  { english: "energetic", category: "Health & Body", difficulty: 1, translation: null },
  { english: "weak", category: "Health & Body", difficulty: 1, translation: "débil" },
  { english: "exercise", category: "Health & Body", difficulty: 1, translation: "ejercicio" },
  { english: "workout", category: "Health & Body", difficulty: 1, translation: null },
  { english: "running", category: "Health & Body", difficulty: 1, translation: null },
  { english: "walking", category: "Health & Body", difficulty: 1, translation: null },
  { english: "swimming", category: "Health & Body", difficulty: 1, translation: null },
  { english: "cycling", category: "Health & Body", difficulty: 1, translation: null },
  { english: "yoga", category: "Health & Body", difficulty: 1, translation: null },
  { english: "meditation", category: "Health & Body", difficulty: 1, translation: null },
  { english: "sleep", category: "Health & Body", difficulty: 1, translation: "dormir" },
  { english: "rest", category: "Health & Body", difficulty: 1, translation: null },
  { english: "diet", category: "Health & Body", difficulty: 1, translation: null },
  { english: "nutrition", category: "Health & Body", difficulty: 1, translation: null },
  { english: "vitamin", category: "Health & Body", difficulty: 1, translation: null },
  { english: "mineral", category: "Health & Body", difficulty: 1, translation: null },
  { english: "protein", category: "Health & Body", difficulty: 1, translation: null },
  { english: "carb", category: "Health & Body", difficulty: 1, translation: null },
  { english: "fiber", category: "Health & Body", difficulty: 1, translation: null },
  { english: "fat", category: "Health & Body", difficulty: 1, translation: null },
  { english: "sugar", category: "Health & Body", difficulty: 1, translation: null },
  { english: "salt", category: "Health & Body", difficulty: 1, translation: null },
  { english: "wash", category: "Health & Body", difficulty: 1, translation: null },
  { english: "clean", category: "Health & Body", difficulty: 1, translation: "limpio" },
  { english: "brush", category: "Health & Body", difficulty: 1, translation: null },
  { english: "floss", category: "Health & Body", difficulty: 1, translation: null },
  { english: "shower", category: "Health & Body", difficulty: 1, translation: null },
  { english: "bath", category: "Health & Body", difficulty: 1, translation: null },
  { english: "soap", category: "Health & Body", difficulty: 1, translation: null },
  { english: "shampoo", category: "Health & Body", difficulty: 1, translation: null },
  { english: "towel", category: "Health & Body", difficulty: 1, translation: null },
  { english: "mirror", category: "Health & Body", difficulty: 1, translation: null },
];

/** Helper: get words by category */
export function getWordsByCategory(categoryName) {
  return WORDS.filter(w => w.category === categoryName);
}

/** Helper: get random words (optionally from a category) */
export function getRandomWords(count = 10, categoryName = null) {
  const pool = categoryName
    ? WORDS.filter(w => w.category === categoryName)
    : WORDS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

/** Helper: get the preloaded translation for a word */
export function getPreloadedTranslation(englishWord) {
  return PRELOADED_TRANSLATIONS[englishWord.toLowerCase()] || null;
}